version: '3'
services:
    php:
        container_name: php-7.4
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        volumes:
            - ./:/www
        networks:
            - app-network

    nginx:
        container_name: nginx
        image: nginx:1.17
        ports:
            - 8080:8080
        volumes:
            - ./:/app
            - ./build/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network

    db:
        container_name: mysql
        image: mysql:5.7
        env_file:
            - .env
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - app-network

volumes:
    db-data:

networks:
    app-network:
        driver: bridge
